trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    echo >> https://aka.ms/yaml
    ls -la
    java -version
    sudo apt-get install groovy
    groovy -version
    gradle -v
  displayName: 'Prepare for tests'
