trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    echo >> https://aka.ms/yaml
    java -version
    gradle -v
  displayName: 'Prepare for tests'
  
- script: |
    gradle test
  displayName: 'Test project'
